# Generated by Django 3.2.7 on 2021-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('system_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
